config/routes.rb
Rails.application.routes.draw do
  devise_for :users, contorollers:{
  	sessions: 'users/sessions',
  	passwords:     'admins/passwords',
  	registrations: 'admins/registrations'
  }
  namespace :admins do
  	resources :learns
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, contorollers:{
  	sessions: 'admins/sessions',
  	passwords:     'admins/passwords',
  	registrations: 'admins/registrations'
  }
  namespace :users do
  	resources :learns, only: [:index, :show]
  end

  root 'homes#top'
  get '/homes/about' => 'homes#about'
end

app/models/learn.rb
class Learn < ApplicationRecord
end

app/controllers/admins/learns_controller.rb
class Admins::LearnsController < ApplicationController

	# before_action: set_learn, only
	def new
		@learn = Learn.new
	end

	def create
		learn = Learn.new(learn_params)
		if learn.save
			redirect_to admins_learns_path
		else
			redirect_to root_path
		end
	end

	def index
		@learns = Learn.all
	end

	def show
		@learn = Learn.find(params[:id])
	end

	def edit
		@learn = Learn.find(params[:id])
	end

	def update
		@learn = Learn.find(params[:id])
		if @learn.update(learn_params)
			redirect_to admins_learn_path(@learn.id)
		else
			redirect_to admins_learns_path
		end
	end

	def destroy
		@learn = Learn.find(params[:id])
		if @learn.destroy
			redirect_to admins_learns_path
		else
			redirect_to admins_learn_path(@learn.id)
		end
	end

	def destroy
	end

	private
	# def set_learn
	# 	@learn = Learn.find(params[:id])
	# end

	def learn_params
		params.require(:learn).permit(:part,
			                          :title,
			                          :subtitle,
			                          :explanation,
			                          :example_essential_thinking,
			                          :example_non_essential_thinking)
	end
end

app/controllers/users/learns_controller.rb
class Users::LearnsController < ApplicationController

	def index
		@learns = Learn.all
	end

	def show
		@learn = Learn.find(params[:id])
	end
end

app/helpers/admins/learns_helper.rb
module Admins::LearnsHelper
end

app/helpers/users/learns_helper.rb
module Users::LearnsHelper
end

app/views/admins/learns/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-offset-1 col-sm-10">
			<h2>Learn編集ページ</h2>

			<%= form_with(model: @learn, url: admins_learn_path(@learn), local: true ) do |f| %>
			    <h4>Part Number</h4>
			    <div class="field form-group">
				    <%= f.label :番号 %>
				    <%= f.select :part ,[["Part1","Part1"],["Part2","Part2"],["Part3","Part3"],["Part4","Part4"]], include_blank: "--下記より選択--" %>
				</div>

				<h4>Title</h4>
				<div class="field form-group">
					<%= f.label :タイトル%>
					<%= f.text_field :title %>
				</div>

				<h4>Subtitle
				<div class="field form-group">
					<%= f.label :サブタイトル %>
					<%= f.text_field :subtitle %>
				</div>

				<h4>Explanation</h4>
				<div class="field form-group">
					<%= f.label :説明文%>
					<%= f.text_area :explanation %>
				</div>

				<h4>Essential Thinking</h4>
				<div class="field form-group">
					<%= f.label :非エッセンシャル思考の例 %>
					<%= f.text_area :example_non_essential_thinking %>
				</div>

				<h4>Non Essential Thinking</h4>
				<div class="field form-group">
					<%= f.label :エッセンシャル思考の例 %>
					<%= f.text_area :example_essential_thinking %>
				</div>

				<%= f.submit 'Update' %>
			<% end %>
		</div>
	</div>
</div>

app/views/admins/learns/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-offset-1 col-sm-10">
			<h2>管理者用　Learn一覧</h2>
			<%= link_to '作成ページ', new_admins_learn_path, class: "btn btn-primary btn-sm" %>
			<% @learns.each do |learn| %>
			    <div>
			    	<h4>id</h4>
			    	<%= link_to admins_learn_path(learn) do %>
			    	    <%= learn.id %>
			    	<% end %>
			    	<h4>パート</h4>
			    	<%= learn.part %>
<!-- 			    	<h3>タイトル</h3>
			    	<%= learn.title %>
			    	<h3>サブタイトル</h3>
			    	<%= learn.subtitle %>
			    	<h3>説明文</h3>
			    	<%= learn.explanation %>
			    	<h3>非エッセンシャル思考例</h3>
			    	<%= learn.example_non_essential_thinking %>
			    	<h3>エッセンシャル思考例</h3>
			    	<%= learn.example_essential_thinking %> -->
			    </div>
			<% end %>
		</div>
	</div>
</div>

app/views/admins/learns/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-offset-1 col-sm-10">
			<h2>Learn作成ページ</h2>

			<%= form_with(model: @learn, url: admins_learns_path, local: true ) do |f| %>
			    <h4>Part Number</h4>
			    <div class="field form-group">
				    <%= f.label :番号 %>
				    <%= f.select :part ,[["Part1","Part1"],["Part2","Part2"],["Part3","Part3"],["Part4","Part4"]], include_blank: "--下記より選択--" %>
				</div>

				<h4>Title</h4>
				<div class="field form-group">
					<%= f.label :タイトル%>
					<%= f.text_field :title %>
				</div>

				<h4>Subtitle
				<div class="field form-group">
					<%= f.label :サブタイトル %>
					<%= f.text_field :subtitle %>
				</div>

				<h4>Explanation</h4>
				<div class="field form-group">
					<%= f.label :説明文%>
					<%= f.text_area :explanation %>
				</div>

				<h4>Essential Thinking</h4>
				<div class="field form-group">
					<%= f.label :非エッセンシャル思考の例 %>
					<%= f.text_area :example_non_essential_thinking %>
				</div>

				<h4>Non Essential Thinking</h4>
				<div class="field form-group">
					<%= f.label :エッセンシャル思考の例 %>
					<%= f.text_area :example_essential_thinking %>
				</div>

				<%= f.submit 'Create' %>
			<% end %>
		</div>
	</div>
</div>

app/views/admins/learns/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-offset-1 col-sm-10">
			<h2>管理者用　Learn詳細</h2>
			    <div>
			    	<h4>id</h4>
			    	<%= @learn.id %>
			    	<h4>パート</h4>
			    	<%= link_to edit_admins_learn_path(@learn) do %>
			    	    <%= @learn.part %>
			    	<% end %>
			    	<h3>タイトル</h3>
			    	<%= @learn.title %>
			    	<h3>サブタイトル</h3>
			    	<%= @learn.subtitle %>
			    	<h3>説明文</h3>
			    	<%= @learn.explanation %>
			    	<h3>非エッセンシャル思考例</h3>
			    	<%= @learn.example_non_essential_thinking %>
			    	<h3>エッセンシャル思考例</h3>
			    	<%= @learn.example_essential_thinking %>
			    </div>
			    <%= link_to '編集する', edit_admins_learn_path(@learn), class: "btn btn-primary col-sm-2"%>
			    <span>&emsp;</span>
			    <%= link_to '削除する（削除ができない）', admins_learn_path(@learn), class: "btn btn-danger btn-sm", method: :delete, data: {confirm: "本当に削除してもよろしいですか？"} %>
		</div>
	</div>
</div>